-- Seed data: 3 sample gyms
INSERT INTO organizations (id, name, name_ne, slug, description, description_ne, address, address_ne, phone, email) VALUES
    ('a1b2c3d4-e5f6-7890-abcd-ef1234567801',
     'Fitness Zone Kathmandu', 'फिटनेस जोन काठमाडौं',
     'fitness-zone-kathmandu',
     'Premium fitness center in the heart of Kathmandu with modern equipment and experienced trainers.',
     'आधुनिक उपकरण र अनुभवी प्रशिक्षकहरूसहित काठमाडौंको मुटुमा प्रिमियम फिटनेस सेन्टर।',
     'Thamel, Kathmandu', 'थामेल, काठमाडौं',
     '9841000001', 'info@fitnesszonektm.com'),

    ('a1b2c3d4-e5f6-7890-abcd-ef1234567802',
     'Power House Pokhara', 'पावर हाउस पोखरा',
     'power-house-pokhara',
     'Lakeside gym offering strength training, cardio, and yoga classes with mountain views.',
     'पहाडको दृश्यसहित शक्ति प्रशिक्षण, कार्डियो र योग कक्षाहरू प्रदान गर्ने लेकसाइड जिम।',
     'Lakeside, Pokhara', 'लेकसाइड, पोखरा',
     '9841000002', 'info@powerhousepokhara.com'),

    ('a1b2c3d4-e5f6-7890-abcd-ef1234567803',
     'Iron Temple Lalitpur', 'आयरन टेम्पल ललितपुर',
     'iron-temple-lalitpur',
     'Community-focused gym with affordable packages and group training sessions.',
     'सस्तो प्याकेजहरू र समूह प्रशिक्षण सत्रहरूसहित समुदायमा केन्द्रित जिम।',
     'Pulchowk, Lalitpur', 'पुल्चोक, ललितपुर',
     '9841000003', 'info@irontempleltp.com');

-- Seed data: Preset workout templates (global, no org)
INSERT INTO workout_templates (id, organization_id, name, name_ne, description, description_ne, category, difficulty, duration_minutes, exercises, is_preset) VALUES
    ('b1b2c3d4-e5f6-7890-abcd-ef1234567801',
     NULL,
     'Full Body Beginner', 'पूरा शरीर सुरुवात',
     'A balanced full-body workout for those just starting their fitness journey.',
     'फिटनेस यात्रा सुरु गर्नेहरूको लागि सन्तुलित पूरा शरीर व्यायाम।',
     'full_body', 'beginner', 45,
     '[{"name": "Bodyweight Squats", "name_ne": "बडीवेट स्क्वाट", "sets": 3, "reps": 12, "rest_seconds": 60},
       {"name": "Push-ups", "name_ne": "पुश-अप", "sets": 3, "reps": 10, "rest_seconds": 60},
       {"name": "Dumbbell Rows", "name_ne": "डम्बेल रो", "sets": 3, "reps": 10, "rest_seconds": 60},
       {"name": "Plank", "name_ne": "प्ल्यांक", "sets": 3, "reps": 1, "rest_seconds": 45, "notes": "Hold for 30 seconds"},
       {"name": "Lunges", "name_ne": "लन्ज", "sets": 3, "reps": 10, "rest_seconds": 60}]'::jsonb,
     true),

    ('b1b2c3d4-e5f6-7890-abcd-ef1234567802',
     NULL,
     'Upper Body Strength', 'माथिल्लो शरीर शक्ति',
     'Build upper body muscle with compound and isolation movements.',
     'कम्पाउन्ड र आइसोलेसन मुभमेन्टहरूसँग माथिल्लो शरीरको मांसपेशी बनाउनुहोस्।',
     'upper_body', 'intermediate', 60,
     '[{"name": "Bench Press", "name_ne": "बेन्च प्रेस", "sets": 4, "reps": 8, "rest_seconds": 90},
       {"name": "Overhead Press", "name_ne": "ओभरहेड प्रेस", "sets": 3, "reps": 10, "rest_seconds": 90},
       {"name": "Barbell Rows", "name_ne": "बारबेल रो", "sets": 4, "reps": 8, "rest_seconds": 90},
       {"name": "Dumbbell Curls", "name_ne": "डम्बेल कर्ल", "sets": 3, "reps": 12, "rest_seconds": 60},
       {"name": "Tricep Dips", "name_ne": "ट्राइसेप डिप्स", "sets": 3, "reps": 10, "rest_seconds": 60},
       {"name": "Lateral Raises", "name_ne": "ल्याटरल रेज", "sets": 3, "reps": 12, "rest_seconds": 60}]'::jsonb,
     true),

    ('b1b2c3d4-e5f6-7890-abcd-ef1234567803',
     NULL,
     'Lower Body Power', 'तल्लो शरीर शक्ति',
     'Leg-focused workout for building strength and power.',
     'शक्ति र पावर निर्माणको लागि खुट्टामा केन्द्रित व्यायाम।',
     'lower_body', 'intermediate', 55,
     '[{"name": "Barbell Squats", "name_ne": "बारबेल स्क्वाट", "sets": 4, "reps": 8, "rest_seconds": 120},
       {"name": "Romanian Deadlifts", "name_ne": "रोमानियन डेडलिफ्ट", "sets": 4, "reps": 8, "rest_seconds": 90},
       {"name": "Leg Press", "name_ne": "लेग प्रेस", "sets": 3, "reps": 12, "rest_seconds": 90},
       {"name": "Walking Lunges", "name_ne": "वाकिंग लन्ज", "sets": 3, "reps": 12, "rest_seconds": 60},
       {"name": "Calf Raises", "name_ne": "काफ रेज", "sets": 4, "reps": 15, "rest_seconds": 45}]'::jsonb,
     true),

    ('b1b2c3d4-e5f6-7890-abcd-ef1234567804',
     NULL,
     'HIIT Cardio Blast', 'HIIT कार्डियो ब्लास्ट',
     'High-intensity interval training for maximum calorie burn.',
     'अधिकतम क्यालोरी बर्नको लागि उच्च-तीव्रता अन्तराल प्रशिक्षण।',
     'cardio', 'advanced', 30,
     '[{"name": "Burpees", "name_ne": "बर्पी", "sets": 4, "reps": 10, "rest_seconds": 30},
       {"name": "Mountain Climbers", "name_ne": "माउन्टेन क्लाइम्बर", "sets": 4, "reps": 20, "rest_seconds": 30},
       {"name": "Jump Squats", "name_ne": "जम्प स्क्वाट", "sets": 4, "reps": 15, "rest_seconds": 30},
       {"name": "High Knees", "name_ne": "हाइ नीज", "sets": 4, "reps": 30, "rest_seconds": 30},
       {"name": "Box Jumps", "name_ne": "बक्स जम्प", "sets": 4, "reps": 10, "rest_seconds": 30}]'::jsonb,
     true),

    ('b1b2c3d4-e5f6-7890-abcd-ef1234567805',
     NULL,
     'Core & Flexibility', 'कोर र लचिलोपन',
     'Strengthen your core and improve flexibility with this balanced routine.',
     'यो सन्तुलित दिनचर्यासँग आफ्नो कोर बलियो बनाउनुहोस् र लचिलोपन सुधार गर्नुहोस्।',
     'core', 'beginner', 35,
     '[{"name": "Plank", "name_ne": "प्ल्यांक", "sets": 3, "reps": 1, "rest_seconds": 45, "notes": "Hold for 45 seconds"},
       {"name": "Russian Twists", "name_ne": "रसियन ट्विस्ट", "sets": 3, "reps": 20, "rest_seconds": 45},
       {"name": "Bicycle Crunches", "name_ne": "बाइसिकल क्रन्च", "sets": 3, "reps": 20, "rest_seconds": 45},
       {"name": "Dead Bug", "name_ne": "डेड बग", "sets": 3, "reps": 10, "rest_seconds": 45},
       {"name": "Cat-Cow Stretch", "name_ne": "क्याट-काउ स्ट्रेच", "sets": 3, "reps": 10, "rest_seconds": 30},
       {"name": "Seated Forward Fold", "name_ne": "बसेर अगाडि झुकाइ", "sets": 2, "reps": 1, "rest_seconds": 30, "notes": "Hold for 30 seconds"}]'::jsonb,
     true);

-- Seed data: Achievement definitions
INSERT INTO achievements (id, name, name_ne, description, description_ne, icon_url, criteria) VALUES
    ('c1b2c3d4-e5f6-7890-abcd-ef1234567801',
     'First Check-in', 'पहिलो चेक-इन',
     'Complete your first gym check-in.', 'आफ्नो पहिलो जिम चेक-इन पूरा गर्नुहोस्।',
     NULL, '{"type": "check_in_count", "value": 1}'::jsonb),

    ('c1b2c3d4-e5f6-7890-abcd-ef1234567802',
     'Week Warrior', 'हप्ता योद्धा',
     'Maintain a 7-day check-in streak.', '७ दिनको चेक-इन स्ट्रिक कायम राख्नुहोस्।',
     NULL, '{"type": "streak", "value": 7}'::jsonb),

    ('c1b2c3d4-e5f6-7890-abcd-ef1234567803',
     'Monthly Champion', 'मासिक च्याम्पियन',
     'Maintain a 30-day check-in streak.', '३० दिनको चेक-इन स्ट्रिक कायम राख्नुहोस्।',
     NULL, '{"type": "streak", "value": 30}'::jsonb),

    ('c1b2c3d4-e5f6-7890-abcd-ef1234567804',
     'Century Club', 'शतक क्लब',
     'Complete 100 workout sessions.', '१०० वर्कआउट सत्रहरू पूरा गर्नुहोस्।',
     NULL, '{"type": "workout_count", "value": 100}'::jsonb),

    ('c1b2c3d4-e5f6-7890-abcd-ef1234567805',
     'Early Bird', 'बिहानी चरा',
     'Check in before 7 AM.', 'बिहान ७ बजेअघि चेक-इन गर्नुहोस्।',
     NULL, '{"type": "early_check_in", "value": 7}'::jsonb),

    ('c1b2c3d4-e5f6-7890-abcd-ef1234567806',
     'Iron Will', 'फलामको इच्छाशक्ति',
     'Maintain a 90-day check-in streak.', '९० दिनको चेक-इन स्ट्रिक कायम राख्नुहोस्।',
     NULL, '{"type": "streak", "value": 90}'::jsonb),

    ('c1b2c3d4-e5f6-7890-abcd-ef1234567807',
     'Year of Dedication', 'समर्पणको वर्ष',
     'Maintain a 365-day check-in streak.', '३६५ दिनको चेक-इन स्ट्रिक कायम राख्नुहोस्।',
     NULL, '{"type": "streak", "value": 365}'::jsonb),

    ('c1b2c3d4-e5f6-7890-abcd-ef1234567808',
     'First Workout Log', 'पहिलो वर्कआउट लग',
     'Log your first workout session.', 'आफ्नो पहिलो वर्कआउट सत्र लग गर्नुहोस्।',
     NULL, '{"type": "workout_count", "value": 1}'::jsonb);

-- Seed data: SaaS plans
INSERT INTO saas_plans (id, name, name_ne, description, description_ne, price_monthly, price_yearly, features, max_members) VALUES
    ('d1b2c3d4-e5f6-7890-abcd-ef1234567801',
     'Starter', 'स्टार्टर',
     'Perfect for small gyms just getting started.',
     'सुरु गर्दै गरेका साना जिमहरूको लागि उत्तम।',
     2999.00, 29990.00,
     '["Up to 50 members", "Basic attendance tracking", "Manual check-in", "Email support"]'::jsonb,
     50),

    ('d1b2c3d4-e5f6-7890-abcd-ef1234567802',
     'Professional', 'प्रोफेशनल',
     'For growing gyms that need advanced features.',
     'उन्नत सुविधाहरू चाहिने बढ्दो जिमहरूको लागि।',
     5999.00, 59990.00,
     '["Up to 200 members", "NFC + QR check-in", "Workout templates", "Analytics dashboard", "Push notifications", "Priority support"]'::jsonb,
     200),

    ('d1b2c3d4-e5f6-7890-abcd-ef1234567803',
     'Enterprise', 'इन्टरप्राइज',
     'Unlimited everything for large fitness chains.',
     'ठूला फिटनेस चेनहरूको लागि असीमित सबै कुरा।',
     9999.00, 99990.00,
     '["Unlimited members", "All check-in methods", "Custom workout plans", "Full analytics", "Multi-location support", "API access", "Dedicated support", "White-label option"]'::jsonb,
     NULL);
