-- Remove all seeded exercises by name.
DELETE FROM exercises WHERE name IN (
    'Push-ups',
    'Wide Push-ups',
    'Diamond Push-ups',
    'Decline Push-ups',
    'Squats',
    'Jump Squats',
    'Lunges',
    'Reverse Lunges',
    'Burpees',
    'Mountain Climbers',
    'Plank',
    'Side Plank',
    'Jumping Jacks',
    'High Knees',
    'Butt Kicks',
    'Bicycle Crunches',
    'Russian Twists',
    'Leg Raises',
    'Flutter Kicks',
    'V-ups',
    'Superman',
    'Glute Bridges',
    'Wall Sit',
    'Tricep Dips (Bodyweight)',
    'Bear Crawl',
    'Inchworm',
    'Tuck Jumps',
    'Box Jumps',
    'Skater Jumps',
    'Dumbbell Rows',
    'Goblet Squats',
    'Dumbbell Lunges',
    'Dumbbell Bench Press',
    'Lateral Raises',
    'Bicep Curls',
    'Tricep Extensions',
    'Dumbbell Deadlift',
    'Dumbbell Shoulder Press',
    'Barbell Bench Press',
    'Barbell Squat',
    'Barbell Deadlift',
    'Overhead Press',
    'Barbell Row',
    'Romanian Deadlift',
    'Cat-Cow Stretch',
    'Downward Dog',
    'Child''s Pose',
    'Pigeon Stretch',
    'Forward Fold',
    'Cobra Stretch'
);
