package nfc

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log/slog"
	"strings"

	"github.com/urja-gym/urja/internal/attendance"
)

// Service handles NFC card business logic.
type Service struct {
	repo              *Repository
	attendanceService *attendance.Service
	logger            *slog.Logger
}

// NewService creates a new NFC service.
func NewService(repo *Repository, attendanceService *attendance.Service, logger *slog.Logger) *Service {
	return &Service{repo: repo, attendanceService: attendanceService, logger: logger}
}

// DeviceCheckInResult is returned to the ESP32 device after a card tap.
type DeviceCheckInResult struct {
	Success    bool   `json:"success"`
	MemberName string `json:"member_name"`
	Streak     int    `json:"streak"`
}

// hashDeviceSecret returns the SHA-256 hex digest of a device secret.
func hashDeviceSecret(secret string) string {
	h := sha256.Sum256([]byte(secret))
	return hex.EncodeToString(h[:])
}

// ListCards retrieves NFC cards for an organization.
func (s *Service) ListCards(ctx context.Context, orgID string, limit, offset int) ([]CardResponse, int, error) {
	if limit <= 0 || limit > 100 {
		limit = 20
	}
	if offset < 0 {
		offset = 0
	}

	cards, total, err := s.repo.ListCards(ctx, orgID, limit, offset)
	if err != nil {
		return nil, 0, err
	}

	responses := make([]CardResponse, len(cards))
	for i, c := range cards {
		responses[i] = c.ToResponse()
	}
	return responses, total, nil
}

// RegisterCard registers a new NFC card for an organization.
func (s *Service) RegisterCard(ctx context.Context, orgID, cardHex string) (*CardResponse, error) {
	cardHex = strings.TrimSpace(cardHex)
	if cardHex == "" {
		return nil, fmt.Errorf("card_hex is required")
	}

	// Validate hex format (basic check: alphanumeric, reasonable length)
	if len(cardHex) < 4 || len(cardHex) > 50 {
		return nil, fmt.Errorf("invalid card_hex length: must be 4-50 characters")
	}

	card, err := s.repo.RegisterCard(ctx, orgID, cardHex)
	if err != nil {
		return nil, fmt.Errorf("registering card: %w", err)
	}

	s.logger.Info("nfc card registered",
		"org_id", orgID,
		"card_id", card.ID,
		"card_number", card.DisplayCardNumber(),
	)

	resp := card.ToResponse()
	return &resp, nil
}

// AssignCard assigns an NFC card to a member.
func (s *Service) AssignCard(ctx context.Context, cardID, orgID, userID string) (*CardResponse, error) {
	if userID == "" {
		return nil, fmt.Errorf("user_id is required")
	}

	card, err := s.repo.AssignCard(ctx, cardID, orgID, userID)
	if err != nil {
		return nil, err
	}

	// Fetch the full card with user name for response
	fullCard, err := s.repo.GetCardByID(ctx, cardID, orgID)
	if err != nil {
		// Assignment succeeded but name lookup failed — use what we have
		resp := card.ToResponse()
		return &resp, nil
	}

	s.logger.Info("nfc card assigned",
		"org_id", orgID,
		"card_id", cardID,
		"user_id", userID,
		"card_number", fullCard.DisplayCardNumber(),
	)

	resp := fullCard.ToResponse()
	return &resp, nil
}

// UnassignCard removes user assignment from an NFC card.
func (s *Service) UnassignCard(ctx context.Context, cardID, orgID string) (*CardResponse, error) {
	card, err := s.repo.UnassignCard(ctx, cardID, orgID)
	if err != nil {
		return nil, err
	}

	s.logger.Info("nfc card unassigned",
		"org_id", orgID,
		"card_id", cardID,
		"card_number", card.DisplayCardNumber(),
	)

	resp := card.ToResponse()
	return &resp, nil
}

// ListDevices retrieves NFC devices for an organization.
func (s *Service) ListDevices(ctx context.Context, orgID string) ([]Device, error) {
	return s.repo.ListDevices(ctx, orgID)
}

// RegisterDevice registers an NFC reader device. The deviceSecret is the raw secret
// generated by the ESP32 on first boot (shown on serial). The backend stores only
// the SHA-256 hash — the raw secret never leaves the device.
func (s *Service) RegisterDevice(ctx context.Context, orgID, name, deviceIdentifier, deviceSecret string) (*Device, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, fmt.Errorf("name is required")
	}
	deviceIdentifier = strings.TrimSpace(deviceIdentifier)
	if deviceIdentifier == "" {
		return nil, fmt.Errorf("device_identifier is required")
	}
	deviceSecret = strings.TrimSpace(deviceSecret)
	if len(deviceSecret) < 16 {
		return nil, fmt.Errorf("device_secret must be at least 16 characters")
	}

	keyHash := hashDeviceSecret(deviceSecret)

	device, err := s.repo.RegisterDevice(ctx, orgID, name, deviceIdentifier, keyHash)
	if err != nil {
		return nil, err
	}

	s.logger.Info("nfc device registered",
		"org_id", orgID,
		"device_id", device.ID,
		"name", name,
		"device_identifier", deviceIdentifier,
	)

	return device, nil
}

// DeviceCheckIn handles a card tap on a device. Authenticates via the device's
// secret (hashed and compared against stored hash), looks up the card member,
// and records attendance.
func (s *Service) DeviceCheckIn(ctx context.Context, deviceSecret, cardUID string) (*DeviceCheckInResult, error) {
	cardUID = strings.TrimSpace(strings.ToUpper(cardUID))
	if cardUID == "" {
		return nil, fmt.Errorf("card_uid is required")
	}

	keyHash := hashDeviceSecret(deviceSecret)
	device, err := s.repo.LookupDeviceByKey(ctx, keyHash)
	if err != nil {
		return nil, err
	}

	userID, memberName, err := s.repo.LookupCardMember(ctx, device.OrgID, cardUID)
	if err != nil {
		s.logger.Warn("device check-in: card lookup failed",
			"device_id", device.ID,
			"card_uid", cardUID,
			"error", err,
		)
		return nil, err
	}

	result, err := s.attendanceService.RecordCheckIn(ctx, userID, device.OrgID, "nfc")
	if err != nil {
		return nil, fmt.Errorf("recording check-in: %w", err)
	}

	streak := 0
	if result.Streak != nil {
		streak = result.Streak.CurrentStreak
	}

	s.logger.Info("device check-in successful",
		"device_id", device.ID,
		"member_name", memberName,
		"streak", streak,
	)

	return &DeviceCheckInResult{
		Success:    true,
		MemberName: memberName,
		Streak:     streak,
	}, nil
}

// DeviceHeartbeat updates the device's online status and uptime.
func (s *Service) DeviceHeartbeat(ctx context.Context, deviceSecret string, uptimeSeconds int64) error {
	keyHash := hashDeviceSecret(deviceSecret)
	device, err := s.repo.LookupDeviceByKey(ctx, keyHash)
	if err != nil {
		return err
	}

	return s.repo.UpdateDeviceHeartbeat(ctx, device.ID, uptimeSeconds)
}
